### ISSUE TITLE
NO SYNC

### ISSUE THREAD

**Issue by Albrt2901** [zanonmark/Google-4-TbSync#1]
I can't get google4tbsync to work. At the time of synchronization it gives the following error: servercontac.names is undefined. What is the problem?

**Comment by zanonmark** [comment]
Could you please post the log (or a comprehensive portion of it), possibly hiding the resource names (i.e.: people/*****)?

Before that, are you sure you tried the latest version? I'm synchronizing the contacts perfectly, which is:
* create / update / delete from Google to Thunderbird;
* create / update / delete from Thunderbird to Google.
Maybe you were using an old commit?

Contact group synchronization is under work (at the time of writing, you should only be able to import the group names into the Thunderbird addressbook).

Thanks,
MZ

**Comment by Albrt2901** [comment]
![image](https://user-images.githubusercontent.com/16681045/109188281-0dc76000-7793-11eb-93e3-86155d08f38a.png)

**Comment by Albrt2901** [comment]
![Sin título](https://user-images.githubusercontent.com/16681045/109188950-c1305480-7793-11eb-8f58-27c0ef1d9d4e.png)

**Comment by zanonmark** [comment]
Thanks, but I need the debug log found in the Tools menu.

Thanks,
MZ

**Comment by Albrt2901** [comment]
The console logs contain many names and emails. I send you only the one related to the error to see if that one works for you.

![image](https://user-images.githubusercontent.com/16681045/109381054-3e64e200-78d8-11eb-8871-b3c615d7b63c.png)

**Comment by zanonmark** [comment]
Perfect thanks, fixed!

MZ

**Comment by Albrt2901** [comment]
Now it does sync the contacts!

Contact groups appear, but empty.

These are the errors now:

![image](https://user-images.githubusercontent.com/16681045/109396429-ca572800-7931-11eb-897f-adf343b91d76.png)

Thank you very much for your work

**Comment by zanonmark** [comment]
Yes, I know, it's the current status of the project :)

Contacts should be synchronizing properly.
Contact groups should be created properly, although empty.

The rest is yet to be done. I'm facing a challenging bug, after that it should be much much easier...

Closing this bug because the original problem is gone.

Thanks,
MZ
