### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by seagull** [zanonmark/Google-4-TbSync#10]
Forgive this stupid question but I am at a loss.
Using Thunderbird 78.10.1 x64. There is no "Add-on options" menu like the documentation on Mozilla shows...
![image](https://user-images.githubusercontent.com/241834/117357800-4a0eef00-aead-11eb-9632-1b602698981e.png)
...And there is no ability to configure things from the Add-ons settings.
![image](https://user-images.githubusercontent.com/241834/117357867-5e52ec00-aead-11eb-83b9-f97def8769fb.png)
(This is after clicking 'Manage'.)

Is the latest Thunderbird build not compatible with G4TBSync or have the developers just hidden the options menu?
Thanks

**Comment by zanonmark** [comment]
Hi,

You will find all the options You need just in the proper TbSync account.

As Google-4-TbSync is an add-on to TbSync, You must install this one first. Then You will simply open the TbSync management interface and add a "Google" account. From now on Google-4-TbSync will do its job.

Please let me know if You need any further help.

Thanks,
MZ

**Comment by seagull** [comment]
Yes!
Thanks. I would never have figured that out, obvious though it is now.
Cheers

**Comment by zanonmark** [comment]
Thank You for Your prompt reply.

It's written, but maybe not stressed enough on the Thunderbird Add-ons page. So I think I'll add an additional statement there.

Thanks,
MZ
