### ISSUE TITLE
Installing and syncing seems fine but no contact changes

### ISSUE THREAD

**Issue by Code2702** [zanonmark/Google-4-TbSync#11]
Hi Mark,

First of all: thanks for working on this project to make syncing contacts to Google possible again. 

I do have a small issue however.  I installed TbSync and Google-4TbSync and generated Google credentials, using your very clear instructions and added my Gmail account (which does NOT end with @gmail.com, but my own domain name) to TbSync. All seems fine: 

- The TbSync management screen shows Status 'OK'. 
- When I click 'Synchronize now', status changes to 'Synchronizing' for a few seconds, then to 'OK: [account name]'. Right-clicking 'Open event log' shows an empty logfile.
- When I click on 'Account settings/Check connection', my number of contacts / contact groups is mentioned so it connects to my Google account. 

However, contacts aren't synced after that; the test-contact I added to my Gmail contacts doesn't show in TB (and the other way around, which is normal for this release I understand). I also tried disabling 'read-only mode'; same result. 

Can you help me figuring out what's wrong? Thanks in advance!

![image](https://user-images.githubusercontent.com/36456494/118961924-234cc000-b965-11eb-8fb6-aa943f629927.png)

**Comment by zanonmark** [comment]
Thanks for Your report.

First of all, a small clarification:

> (and the other way around, which is normal for this release I understand)

Only if You checked the "Read-only mode" flag.

As for Your issue, does the contact You added in Google Contacts belong to any group (aka "labels")?

MZ

**Comment by zanonmark** [comment]
Could You please assign it to a label and try again?

Thanks,
MZ

**Comment by Code2702** [comment]
I assigned the test contact to a label and tried again. Even restarted TB, but unfortunately no change....

**Comment by zanonmark** [comment]
Thanks for testing,

then I should check the full log: could You please post the content of the Console? Please remove the sensitive data first.

Thanks,
MZ

**Comment by Code2702** [comment]
Hi Mark, 
I've sent you a PM with the requested log file.

**Comment by zanonmark** [comment]
Closed because fixed, as per private communication.

Thanks,
MZ
