### ISSUE TITLE
When TBird starts up, **all** the addressbooks sync in succession...ka-boom...

### ISSUE THREAD

**Issue by saleslogistix** [zanonmark/Google-4-TbSync#14]
Environment:  Tbird 78.11.0, latest version of this plugin (0.1.14?) plus latest version of TBsync.
Three addressbooks, all in read-write mode synching to three separate accounts in Google.
One addressbook has 410 contacts, the second 800, and a third 9000.  The first two sync just fine in a few seconds.
Guess what happens when you start TBird?  The sync mechanism queues all three addressbooks in a row, instantly...and that third addressbook totally locks up Tbird for many many minutes. Many.  Many.
The Periodic Synchronization normally spreads out the load (the big addressbook runs once a week), but the counter for time evidently starts at zero with a new Tbird run, and at zero they all queue up.  This renders Tbird inoperative for waaaaaaaaaaaayyyyyy tooooooooo looooong.
Approach #1:  have the sync start when the counter reaches the specified number of minutes, not at zero.
Approach #2:  use a random number generator to "seed" the timer for sync, so that (1) it never starts up right away and (2) doesn't start the queuing for all addressbooks immediately.
Approach #3:  if there's a way to have the sync process NOT overwhelm my poor 8-core 2.4 GHz 32 GB RAM system, that could work, too.  Spreading the load over a much longer time....

**Comment by zanonmark** [comment]
Thanks for reporting.

Marked as enhancement, but I'm not sure this issue is 100% related to Google-4-TbSync: maybe part of it deals with TbSync itself.

MZ

p.s.: please be careful when using the sharp (#) sign, it's used to reference other issues...

**Comment by saleslogistix** [comment]
Actually...I mis-stated the issue.  With my new info, this truly is just an enhancement.
Turns out my original statement is not true. What actually is going on:  the timers appear to be working properly, but if one of them happens to trip during a time when Tbird isn't running, when it does start again the sync will dutifully run upon startup.  This makes it look like Tbird is broken.  And if you have small, sensible contact lists, it's not that big a deal.
But if you have one with 9000 contacts, this will go for many minutes.  The work-around is (1) smaller lists and (2) very long auto-sync intervals.

**Comment by zanonmark** [comment]
Ok, keeping the issue freezed for a while because this involves TbSync too, and I'm waiting for major rewrite of it.

Thanks,
MZ

**Comment by gcalzo** [comment]
+1 for me too!
I had to dismiss gContactSync so now I'm using Google-4-TbSync and each time my TB 78.14.0 x86 is **frozen** until the end of my Google's contact (573 contacts) sync.
I'm using TbSync also for my Exchange contacts since long time ago and I never ad a freeze with them (322 contacts)

**Comment by zanonmark** [comment]
Hi all,

could You please check if this still happens with the latest 0.5.2?

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many months without a reply.
