### ISSUE TITLE
Not syncing phone number.

### ISSUE THREAD

**Issue by pistol86** [zanonmark/Google-4-TbSync#15]
Hi Mark. Thank you for your work.

When I create a contact in google only filling Name and phone number without phone type (mobile, home, work...), TbSync does sync the contact name, but not contact phone number.
![Captura de pantalla 2021-06-09 170217](https://user-images.githubusercontent.com/79310237/121380230-ff1d4700-c944-11eb-8a7f-5b4c5cbe16cc.jpg)
![Captura de pantalla 2021-06-09 170313](https://user-images.githubusercontent.com/79310237/121380248-017fa100-c945-11eb-809f-bd20eb2f6fb9.jpg)

Thank you so much.

**Comment by zanonmark** [comment]
> Hi Mark. Thank you for your work.

Thanks for testing.

> When I create a contact in google only filling Name and phone number without phone type (mobile, home, work...), TbSync does sync the contact name, but not contact phone number.

Yes, I only recently discovered that You can enter a phone number with no label at all :)

So: I'm fixing it in a few days (I will probably assign that phone number to the first field in TB, which is "Work").

Thanks,
MZ

**Comment by zanonmark** [comment]
Fixed right now,

0.1.5 will be released shortly.

Thanks,
MZ
