### ISSUE TITLE
Add support for corporate directories

### ISSUE THREAD

**Issue by Marginal** [zanonmark/Google-4-TbSync#18]
People whose account is tied to a corporate GSuite account have a corporate directory as well as personal contacts - https://developers.google.com/people/api/rest/v1/people/listDirectoryPeople

**Comment by zanonmark** [comment]
Thanks for this ticket.

As I don't have a corporate account and can't directly test by myself, could You please tell me the following?
a) Are those contacts read-only? I can't seem to find any method on the documentation page to create or modify them.
b) Would it be ok for You, in Thunderbird, to have them mixed with user contacts?

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ
