### ISSUE TITLE
Webextensions prerequisite timescale

### ISSUE THREAD

**Issue by carterbrandon** [zanonmark/Google-4-TbSync#2]
As the project now has to wait until TBsync gets its port to webextensions, could you include in the readme when you can, any timescale estimates you might get from them? It's just that I can't see any reference to this work on their own TBsync wiki.

**Comment by zanonmark** [comment]
It's not written anywhere because it was an email-only discussion between jobisoft (John Bieling) and me :)

He first estimated a 4-weeks work, due by the end of March 2021, but he just found some issues and the migration is delayed.
I'll keep you up-to-date.

Thanks,
MZ

**Comment by zanonmark** [comment]
I updated the README.

Thanks,
MZ
