### ISSUE TITLE
Google won´ accept any Test User.

### ISSUE THREAD

**Issue by JPRuehmann** [zanonmark/Google-4-TbSync#20]
I cant´t connect to Google Callendars.
It says there is no Test User.
I had entered my Address but it sayd that my Address is incorrect.
How can I make it work?

**Comment by zanonmark** [comment]
Same as Your other issue: Google-4-TbSync is **NOT** for calendars, only for contacts (this is written in this website, in the Mozilla Download page and in the documentation).

Thanks,
MZ
