### ISSUE TITLE
After Thunderbird update to 91.* Google-4-TbSync can't handle contacts that belong to a contact group.

### ISSUE THREAD

**Issue by glotzbam** [zanonmark/Google-4-TbSync#25]
This loop In line 1310 of `AddressBookSynchronizer.js`

```
while (0 < localContactGroupDirectory.childCards.length) {
    localContactGroupDirectory.childCards.pop();
}
```

runs infinite, blocking Thunderbird's main loop as it seems, because for some reason popping the list items won't decrease the `length`-property.

I wasn't able to figure out what exactly happens under the hood and JavaScript isn't my strong suit, but maybe it would be possible to replace this loop with something like `localContactGroupDirectory.childCards = [];` or similar, which doesn't rely on the underlying mechanics of that counter.

EDIT: It works for me if I replace the whole while-loop with `localContactGroupDirectory.childCards.length = 0;`

**Comment by zanonmark** [comment]
Thanks for Your report.

As I'm not experiencing Your issue, could You please re-enable the original code, update all Your softwares (TB 91.3.0, TbSync 3.0.1, Google-4-TbSync 0.2.1) and test again?

Thanks,
MZ

**Comment by zanonmark** [comment]
Just released version 0.2.2 (which will be available tomorrow I believe),

could You please test it and let me know?

Thanks for Your help in debugging,

MZ

**Comment by glotzbam** [comment]
I've tried it (with 91.3.0 because it's the latest version my package manager offers) and it works like a charm. Thank you!

**Comment by zanonmark** [comment]
Thanks for the feedback,

MZ
