### ISSUE TITLE
Chrome closes Google auth code window when I try to access/synchronize google account from TB tools using TBsynch

### ISSUE THREAD

**Issue by Medor17** [zanonmark/Google-4-TbSync#26]
Salve Dottore..
And now Google has blocked my access.
I just saw the auth code flash by really quickly before it closed..

**Comment by zanonmark** [comment]
Hi,

just to summarize: You are running:
* Thunderbird 91.3.x,
* TbSync 3.0.1,
* Google-4-TbSync 0.2.2
right?

And You were using all of those properly with no issues, until a few days ago?

MZ

**Comment by Medor17** [comment]
Buonasera Dottore,


Thank you for your kind attention.

The answer is yes to all your questions. Then again, I'm totally anumerical - I just follow instructions without trying to understand - it's above my capacities.

I basically gave up and imported Google vcards to TB, but that doesn't work either: I do have the adresses in the TB address book, but TB doesn't offer/prompt when I type a name in: for example when I type Roger it doesn't propose my e-mail adress.

It's a minor hassle, it just tees me off to have followed the instructions to the end, and then the miracle doesn't happen.

**Comment by Medor17** [comment]
Update: I am now able to access my Google address book thanks to the addition of a distant server (Google) in the Thunderbird feature (Add-on??) called Cardbook. I am even prompted for adresses from my Google AB when composing a new mail. Quindi, problem solved for the time being, but without the "intellectual" satisfaction of having debugged the first procedure...

**Comment by zanonmark** [comment]
Hi, and sorry for the delay in replying.

It seems to me You could have experienced some JavaScript issues at first (the authorization code window flashing pushes me in this direction, but I can't be sure...).

You seem to have solved by using a different add-on called Cardbook; which works well for synchronizing contacts but not groups (Google's fault here: they don't fully support the CardDAV universal protocol...).

I'm closing this ticket for the moment - but please feel free to reopen if You want to give Google-4-TbSync a new try, in which case I could try and help You...

Thanks,
MZ
