### ISSUE TITLE
CalDAV & CardDAV google authorization

### ISSUE THREAD

**Issue by naasking** [zanonmark/Google-4-TbSync#28]
As mentioned in my prior issue, CalDAV & CardDAV now asks for my Google login every time Thunderbird opens. It doesn't save the authorization even when "don't ask again on this device" is clicked. I've tried deleting the account in TbSync and recreating it, behaviour persists though.

I'm on Thunderbird 91.3.2, TbSync 3.0.1, CalDav 2.0.2, Google-4-TbSync 0.2.2.

**Comment by zanonmark** [comment]
Hi,

I'm sorry, but for "CalDAV & CardDAV" issues You have to open a specific ticket to the Author (I'm the developer of Google-4-TbSync only).

Thanks,
MZ
