### ISSUE TITLE
Where do I find...

### ISSUE THREAD

**Issue by saleslogistix** [zanonmark/Google-4-TbSync#3]
Sorry to be a complete nuub, but I'm unable to find the xpi file for Google-4-TbSync.
I'm happy to accept the risk of using it...but where do I get it?

**Comment by bac8fe** [comment]
Hello, I have the same question: I have created a Google API Console project. But how I can install this Google-4-TbSync? Or till when it is expected to be available? 
Thanks in advance, Chris

**Comment by zanonmark** [comment]
Hi,

the project is still not released officially, so there's no .xpi at the moment.

But you can easily:
* [grab the latest .zip package](https://github.com/zanonmark/Google-4-TbSync/archive/refs/heads/main.zip),
* unzip it wherever you want,
* load it as a temporary add-on from Thunderbird > Tools > Add-ons > cog icon > Debug Add-ons > Load Temporary Add-on (pick manifest.json for example).

Thanks,
MZ

**Comment by zanonmark** [comment]
I also updated the README.

Thanks,
MZ
