### ISSUE TITLE
TB Lists do not transfer to Google Labels

### ISSUE THREAD

**Issue by Andrew-Lohmann** [zanonmark/Google-4-TbSync#30]
Thunderbird version: 78.14 to 91.5 Linux or Windows
I originally posted at: https://github.com/jobisoft/TbSync/issues/558 but I was advised to post the issue here.

My TB address book is organised into lists I pasted each list into the Andrew-Google-4-TbSync and expected those contacts to have google labels added.  The lists are all empty in Google and then subsequently the lists in the Andrew-Google-4-Tb are empty in TB. But all the contacts are present. If I add labels to the contacts in google the contact successfully moves into the list named in TB. 

I previously tried CARDBOOK this put contacts in google contacts. That was removed so it will not conflict with TbSync.

1. Created new lists and copied contacts into those lists from the TB Personal Address book to the Andrew-Google-4-TbSync address book. This looked okay at first.

2. Closed and opened TB found that all the Andrew-Google-4-TbSync lists were empty.  Looked at Contacts.google.com similarly the lists (Labels not marked) were empty.

3. Added a few labels to some contacts in Contacts.google.com and found the contacts then appeared in TB Andrew-Google-4-TbSync the few Lists I changed in google.

Note I do not use Contacts.google.com but wish to use TB contacts. Therefore if someone sends to me from a mail list I will add a new list to TB but this now won't work.

**Comment by zanonmark** [comment]
Hi, and thanks for Your report.

If I didn't misunderstand, You're trying to drag&drop mailing-lists between two local TB addressbooks, right?
If so, it looks like a bad idea :)
I tried to do the same locally and it didn't work - however that's not something my add-on is involved into, but rather a TB issue.
The whole addressbook code is old, old, old.

If You need to do that once, or once per month, I suggest You export the addressbook and then reimport it, without drag&dropping the single items (contacts or lists).

Please let me know if I can be more helpful.

Thanks,
MZ

**Comment by Andrew-Lohmann** [comment]
Thanks MZ,

I do not think that is going to resolve the issue because the address book was recovered from a corrupted new one which I exported for each lists from.  Then I used an good back-up profile that used the old abook.mab file and an older version of TB which I allowed to update and changed the profile.  Finally when I imported each list what I got was an address book for each list which I then needed to highlight and drag.

In short what ever I do I can not see it possible to avoid copy-and-past that you suggest.

I have also experimented with yahoo mail contacts and similarly "Provider for CalDAV & CardDAV" basically transferred the contacts much the same and also merged and rationalised them in a similar way but the lists were not transferred or removed (unlike google) subsequently.  A label created in Yahoo contacts did not transfer back into TB Yahoo address book.   None of the lists transferred back to another installation of Thunderbird on another PC.  - I was going to report this separately but it is closely related.

As for old software nothing wrong with that what is wrong is deficiencies in what TB created.  One of the flaws is that where a contact does not have at least one label or does not exist in a list I do not want it any more.

How I have got the problem is that I used to have one copy of abook.mab on Dropbox and symbolic links to the TB profile.  That worked fine for years until the address book became sqlite

**Comment by Andrew-Lohmann** [comment]
Dealing with your suggestion further I have to look at using google contacts import and see if I can import and attach labels?  but that does not address contacts I add and remove in Thunderbird which is the only place I use contacts.

**Comment by zanonmark** [comment]
Hi Andrew,

sorry for taking long to answer.

Please consider that Google-4-TbSync is still in its early releases.
Particularly, the only thing it surely does not support at the moment is adding / removing contacts to / from local mailing-lists (in TB) and synchronizing this operation to Google.
For this to work, I'm waiting for a new rewrite of TbSync. Only then I will be able to rewrite Google-4-TbSync, and then this feature could be available too.

As for CardBook and Provider for CalDAV & CardDAV, as far as I know those add-ons work with the standard CardDAV protocol: which could be ok for a generic provider, but unfortunately Google does not offer a complete support for it (specifically: no group / label / mailing-list support).

So, I think the only solution for You is currently import everything to Google using the web interface, and then make a read-only synchronization to TB.

Thanks,
MZ

**Comment by Andrew-Lohmann** [comment]
Hi MZ,

I agree and also add that Thunderbird have also added CALDAV and CARDDAV sync this has a R/O tick but only works read only but does not read in labels.  This feature includes automatic settings when you add an email account and may to be new with TB 91.5.1? 

I have been trying to document what to do but all of these address book synchronisation features are changing at the moment; https://engineering.andrew-lohmann.me.uk/windows-2-linux---operating-systems/linux-windows-maintenance#h.fkwlnkdyfb0o

Once again thanks
Andrew
