### ISSUE TITLE
stuck on setup

### ISSUE THREAD

**Issue by sharkmullet** [zanonmark/Google-4-TbSync#31]
I get stuck on step 3, the interface looks very different from the tutorial.

https://github.com/zanonmark/Google-4-TbSync/wiki/How-to-generate-your-own-Google-API-Console-project-credentials

I got a new project created, but then I don't know where to go from there

**Comment by zanonmark** [comment]
Yes, dont' forget to thank Google for this :)

You probably now need to click "Project settings", then open the top-left menu and click "APIs & Services".

See screenshot:
![Screenshot from 2022-02-06 12-32-23](https://user-images.githubusercontent.com/13437344/152678873-1ca514ca-42e7-4a66-a4bf-496eb93b0997.png)

Please let me know if everything is ok.
MZ
