### ISSUE TITLE
Commas in label names cause a sync error

### ISSUE THREAD

**Issue by Chef8** [zanonmark/Google-4-TbSync#32]
If you have a google contacts label name that contains a comma, it will cause a sync error. Workaround is removing the comma. I have not tested any other punctuation. I know hyphens work okay.

**Comment by zanonmark** [comment]
Thanks for Your report.

It seems some characters are invalid in TB:
![1](https://user-images.githubusercontent.com/13437344/155002181-23583231-6370-4ab6-a5ab-50f99d95b436.png)

I'm fixing it. A new version will be available as soon as possible.

Thanks,
MZ

**Comment by zanonmark** [comment]
Fixed.

Thanks,
MZ
