### ISSUE TITLE
Spams to /var/log/syslog?

### ISSUE THREAD

**Issue by tsbertalan** [zanonmark/Google-4-TbSync#34]
Is there any way to get this plugin to stop outputting into /var/log/syslog? I'm finding that my log is spammed with basically complete dumps of my contacts list every few minutes, starting with "AddressBookSynchronizer" and "PeopleAPI.getResponseData" among other things.

It's possible these log insertions aren't due to this plugin--I first asked the author of AddressBookSynchronizer, who kindly pointed out that these log strings wouldn't appear with his plugin, but are likely to with things connected with the Google PeopleAPI. I believe that's this plugin.

**Comment by tsbertalan** [comment]
Ah, I suppose it's implied by the title, but this is on Linux (Ubuntu 20.04).

**Comment by hrford** [comment]
I'm using Kubuntu 20.04 and have just installed TbSync. I don't see any spam in syslog but also didn't enable debug logging. I don't have an issue at the moment but would be happy to help test. Tag me if you need that.

**Comment by zanonmark** [comment]
Hi,

yes, this plugin is using console.log(): how much, depends on the 'Verbose logging' flag.

So the question should be: is it possible for Thunderbird to not log to syslog?
I'm sorry, I don't know if that's possible.

Thanks,
MZ

**Comment by tsbertalan** [comment]
@zanonmark I'm not sure how that flag is set for me. Is this global to Thunderbird, or specific to this plugin? How could I check one way or another?

**Comment by zanonmark** [comment]
It's specific to this plugin; see screenshot.

![Screenshot_2022-04-24_16-40-01](https://user-images.githubusercontent.com/13437344/164981896-413575fa-59ac-49aa-8874-aca97e08b323.png)

Thanks,
MZ

**Comment by tsbertalan** [comment]
Well, that box is currently unchecked (not sure when that happened), and I don't see any `AddressBook` in my syslog, until I go back to syslog.5.gz (April 21). So I guess that solves it for me.

**Comment by zanonmark** [comment]
Before the last version, everything was fully logged.
The last one introduced this checkbox, disabled by default.
You probably just updated the add-on :)

Thanks,
MZ

**Comment by tsbertalan** [comment]
<img src="https://i.imgur.com/6zeve8L.gif" />
