### ISSUE TITLE
addresses do not sync Google -> TBird

### ISSUE THREAD

**Issue by 1MikeMakuch** [zanonmark/Google-4-TbSync#35]
I think this used to work but not now.

TBird 91.7
updated tbsync and google-4-tbsync

It syncs name, email and phone but not address, city state, zip.

Is it supposed to pull addresses?

**Comment by Chef8** [comment]
Did you set the label for the addresses in Google?

**Comment by 1MikeMakuch** [comment]
I don't know anything about this. Is it documented to do this somewhere?
Thanks

**Comment by zanonmark** [comment]
Could you please check the labels as Chef8 said, i.e.:
* address (Work, Home, etc.);
* phone (Work, Work Fax, etc.).

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ
