### ISSUE TITLE
Synchronization of tasks does not work

### ISSUE THREAD

**Issue by uuroveits** [zanonmark/Google-4-TbSync#37]
TbSync version: 3.0.2
Thunderbird version: 91.8.1 (64-Bit)

After successful installation of TbSync (and Google-4-TbSync) and activation and synchronization via People API of Google (status is green) the synchronization of tasks is not possible.

Questions:
1) Are there any instructions on what to consider regarding the synchronization of tasks?
2) What can I do to solve the problem?

regard

Jochen

**Comment by zanonmark** [comment]
Hi,

Google-4-TbSync is for synchronizing contacts only.
No other synchronization (calendars, tasks, etc.) is provided at the moment (and not in the foresesable future).

Thanks,
MZ
