### ISSUE TITLE
Cant add google account to tbSync

### ISSUE THREAD

**Issue by gregor5582** [zanonmark/Google-4-TbSync#39]
Hi
Basically I have no idea what i am doing. I just followed all the steps with the API and stuff and I had no problem at all but when i tried to  add my google account to tbSync, this error messages came up:

Browser window closed before the authorization code was retrieved.

AuthorizationCodeError@chrome://google-4-tbsync/content/includes/AuthorizationCodeError.js:18:9
getNewAuthorizationCode/promise</authenticationWindow.onclose@chrome://google-4-tbsync/content/includes/PeopleAPI.js:145:28

and 

Browser window closed before the authorization code was retrieved.

AuthorizationCodeError@chrome://google-4-tbsync/content/includes/AuthorizationCodeError.js:18:9
getNewAuthorizationCode/promise</authenticationWindow.onclose@chrome://google-4-tbsync/content/includes/PeopleAPI.js:145:28

Is this error easily fixable?

Thanks in advance
Gregor

**Comment by zanonmark** [comment]
Hi,

do you have any particular add-on installed?
anything that could block JavaScript from being executed properly?

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ
