### ISSUE TITLE
Google contacts resets Display field on sync

### ISSUE THREAD

**Issue by sjukfan** [zanonmark/Google-4-TbSync#40]
For my own readability I change the Display field in Thunderbird address book to "Job - Steve" or similar, but when I sync the Thunderbird address book this field is reset to the default First Last name. I haven't been able to find a similar field on Google contacts, only Nickname.

**Comment by zanonmark** [comment]
Thanks for Your ticket.

However, this part will be rewritten in a few weeks when porting to TB102.
Let's see if everything gets fixed by then.

Thanks,
MZ

**Comment by zanonmark** [comment]
Could You please check if the problem persists with the latest 0.4.0?

Thanks,
MZ

**Comment by zanonmark** [comment]
Well, could You please check with the latest 0.5.0 instead?

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ
