### ISSUE TITLE
TB 102?

### ISSUE THREAD

**Issue by peci1** [zanonmark/Google-4-TbSync#41]
Hi Marco, do you plan updating the addon to make it compatible with TB 102?

**Comment by zanonmark** [comment]
Hi Martin,

sure, there will be an upgrade for TB102.

I'm sorry to say it will take some time though... John Bieling is porting TbSync to TB102 by mid July, then he will kindly help me porting Google-4-TbSync, and after that I will need to rewrite part of the code...

I think it will not be ready before mid August.

Thanks,
MZ

**Comment by ikenichiro** [comment]
TbSync now has a branch for [TB102](https://github.com/jobisoft/TbSync/tree/TB102), and I've tested a little by modifying few lines on manifest.json 15fa355592d842c2eb17998ee14e8657178326c9 .
The connection part seems OK, and if there is no new contact, everything seems fine. (Modification of existing card might be OK?)
For a new contact, it fails with a message shown on the TbSync status
```
status. Unable to set FirstName as a property, use vCardProperties
```
I found a thunderbird document that seems to explain about this error, but I couldn't find where I should start checking. https://developer.thunderbird.net/add-ons/updating/tb102/adapt-to-changes-in-thunderbird-92-102

I hope this can give some help!

**Comment by zanonmark** [comment]
@ikenichiro Thanks for Your hint.
Actually, I'm testing locally a 0.4.0 version which seems to be working fine - I had to rewrite completely the mapping methods because Thunderbird now uses vCard and vCardProperties internally...

I hope I'll be able to make a release in a few days.

Thanks,
MZ

**Comment by ikenichiro** [comment]
@zanonmark 
Thanks for the reply.
Testing with the latest Thunderbird (103.3.3), TBSync ([4.3](https://github.com/jobisoft/TbSync/releases/tag/v4.3)), Google-4-TBSync 0.4.0 ([676eef5](https://github.com/zanonmark/Google-4-TbSync/commit/676eef5167bd9b3e4e64208ee3af4e46e9752fca)) creating groups seem OK, none of the contact seems to be created with the following error.

[EventLog] : [JavaScript Error: "design is undefined" {file: "resource:///modules/VCardUtils.jsm" line: 951}]'[JavaScript Error: "design is undefined" {file: "resource:///modules/VCardUtils.jsm" line: 951}]' when calling method: [nsIAbDirectory::addCard]

**Comment by zanonmark** [comment]
@ikenichiro Thanks, that was probably a code change in TB, I'm discussing the matter with John Bieling.

In the meanwhile, John suggested me to edit the code for a workaround... so I could release v 0.4.0.

Thanks,
MZ
