### ISSUE TITLE
Google contact with multi-line notes results in blank TB contact

### ISSUE THREAD

**Issue by mrbumpy409** [zanonmark/Google-4-TbSync#42]
Using current git version of Google-4-TbSync (0.4.0), if a Google contact field contains a newline, the resulting synced Thunderbird contact appears blank (no name or data). This most commonly occurs in the notes field, but I did have an example of a newline in an address field on an older contact. Removing the newlines causes the contact to correctly sync.

**Steps to reproduce:**
1. Create a Google contact.
2. Add two lines of text to the notes field, with a newline (enter key) between them.
3. Synchronize address books via TbSync.

**Result:** The contact shows as a blank entry in the Thunderbird address book.

**Comment by zanonmark** [comment]
Fixed in the upcoming 0.4.1.

Thanks,
MZ

**Comment by mrbumpy409** [comment]
Just tested 0.4.2 and no sign of the bug. Thanks!

**Comment by zanonmark** [comment]
Thanks for confirming.

MZ
