### ISSUE TITLE
Invalid Mail list name: 

### ISSUE THREAD

**Issue by Moryason** [zanonmark/Google-4-TbSync#43]
![error-tbsync](https://user-images.githubusercontent.com/20194980/196495555-fa5ff228-5129-4142-94af-f1745fe41e7c.jpg)

Error in synchronizing groups apparently... Maybe a local chars issue ? Language is French.

**Comment by zanonmark** [comment]
Hi,

could You please open Tools > Developer Tools > Error Console and copy+paste the exact group name?

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ
