### ISSUE TITLE
After upgrade TB to 102.4.0  I have trouble with plugin sign in 

### ISSUE THREAD

**Issue by yardstudio** [zanonmark/Google-4-TbSync#45]
Hello,

I am upgraded TB to 102.4.0 (64 bit) right now and Google-4-TbSync asking me for credential immediately TB starts. I have on Google 2-factor enabled and Apps Passwords generated. But any pass not workig 
![2022-10-24_16-31-44](https://user-images.githubusercontent.com/25852179/197554391-fc975107-1b19-4db2-8114-fcc7879dcf24.png)

Here is TB log:

`URL:
https://apidata.googleusercontent.com/caldav/v2/XXXXXXXXX%40gmail.com/user (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>loginRequired</code>
  <internalReason>Login Required.</internalReason>
 </error>
</errors>`

**Comment by zanonmark** [comment]
Hi,

Your screenshot shows that this issue is not related to Google-4-TbSync, but rather to some other TbSync add-on.

MZ
