### ISSUE TITLE
Problem with synced contact

### ISSUE THREAD

**Issue by BillH99999** [zanonmark/Google-4-TbSync#49]
My primary email address is defined as a contact in Google Contacts.  The name on that contact is my name.  That email address is used as the backup address for my gmail account.  

The name on my gmail account is an abbreviation of my name.

After syncing my Google Contacts to Thunderbird, there is no contact with my name in Thunderbird.  My pimary email address is in a contact which has the abbreviation of my name as the name of the contact.  In other words, somehow the name of my gmail account is being put on the contact in Thunderbird rather than the name from Google Contacts for that contact.  Hope that makes sense.

I would be happy to supply you with screen shots of what the account looks like in Google Contacts and in Thunderbird, but I don't want to post them on this public board.  If you would like them is there an alternative way to get them to you?

Thanks,
Bill

**Comment by zanonmark** [comment]
Hi,

please contact me privately at info@marcozanon.com, where You can send screenshots and the log from Tools > Developer Tools > Error console (I need to see what Google-4-TbSync grabs from the Google servers...).

I suspect this may have something to do with how Google stores those information, but we shall see...

Thanks,
MZ

**Comment by BillH99999** [comment]
Marco,

I am sending some info via email.

Thanks,
Bill

**Comment by zanonmark** [comment]
Closed as per private communication.

Thanks,
MZ
