### ISSUE TITLE
Wiki update of scopes

### ISSUE THREAD

**Issue by 29039** [zanonmark/Google-4-TbSync#51]
Sorry I can't figure out how to update the Wiki myself.

on: https://github.com/zanonmark/Google-4-TbSync/wiki/How-to-generate-your-own-Google-Cloud-Console-project-credentials

Where it has scopes, can you please put in a box with the scopes already formatted for a copy & paste. It would make it a bit easier.

Instead of: 
`"https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email" (which will be displayed in Your non-sensitive scopes) and "https://www.googleapis.com/auth/contacts" `

Write it out as:

```
https://www.googleapis.com/auth/userinfo.profile
https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/contacts
```

That would be great, thanks!

**Comment by zanonmark** [comment]
Done, thanks.
MZ
