### ISSUE TITLE
Cannot use - Can't get out of Testing the API

### ISSUE THREAD

**Issue by ChasLarge** [zanonmark/Google-4-TbSync#52]
Just changed to ThunderBird from Outlook.
Just installed TbSync
Followed the Google instructions to set up the API as per your guidlines.
Went to enable the account in TbSync and was told, cannot access as the API is still in testing mode.
Went to the API and tried to publish, but it then asked for Web Page and much more that I don't have. Yes I can create a dummy page on my website but surely this is all going far overboard.
I just can't be doing with all this faffing about. Surely there's a simpler way or better guidelines on setting up this sync? 
Sorry to moan but.... 
Any advice?

**Comment by zanonmark** [comment]
Hi,

my guess is You probably missed some steps when creating the credentials, because using the app in Testing mode is perfectly doable.

Could You please check step-by-step?
After that, ping me back if You need help.

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without a reply.
Feel free to reopen if the problem persists.

MZ

**Comment by ChasLarge** [comment]
I have not received any messages from you about this issue, please resend
your questions.

Regards
Charles
