### ISSUE TITLE
Custom labels for user.phonenumbers

### ISSUE THREAD

**Issue by juanjosepablos** [zanonmark/Google-4-TbSync#53]
I am testing you Thunderbird plugin, and so far works great!, but i notice that some of my contacts have a custom label for phone numbers other than "Work,Home,Fax", when are synchronized the label show as "None". But i feel that this should be replaced by the custom string.
Here is the API
https://developers.google.com/people/api/rest/v1/people#Person.PhoneNumber

The change feels like it should be here:
https://github.com/zanonmark/Google-4-TbSync/blob/b9aecf27179bee2491e6db6ebfb8d91bb1381e19/content/includes/AddressBookSynchronizer.js#L531

before pushing some request, What do you thing?

**Comment by zanonmark** [comment]
Thanks for writing, and sorry for my late reply.

The point is: currently, the TB addressbook only has a few valid labels for phone numbers: Work, Home, Cell, Fax, Pager, None.
You cannot use custom labels locally (in the TB addressbook).
So I wouldn't know how to store them.

Thanks,
MZ

**Comment by zanonmark** [comment]
Closing because it can't be fixed at the moment.

MZ

**Comment by juanjosepablos** [comment]
Thanks So Much!
