### ISSUE TITLE
TB 115

### ISSUE THREAD

**Issue by BillH99999** [zanonmark/Google-4-TbSync#55]
Marco, 

I'm sure you are already working on an update for TB 115.  Any estimated time frame for when it might be available?  I won't hold you to this and I'm not trying to rush you or anything.  I'm just curious.

Thanks,
Bill

**Comment by MSBlueVn** [comment]
Same here

**Comment by andrearesti** [comment]
Hi Marco, any plans to update to 115? Anyway, thanks for the terrific work you have done on this.

**Comment by martindaehn23** [comment]
Same here, awesome work! This addon would save me a lot of user complains, but we are running on 115 ...

**Comment by BillH99999** [comment]
Now that TbSync for Thunderbird 115 has been released is there any loose timeline for when an updated Google-4-TbSync might be released?

**Comment by zanonmark** [comment]
Hi everyone,

yes, I knew TB115 introduced some changes and Google-4-TbSync was no longer working, but I was waiting for TbSync to be upgraded.
Now that it's out, I will try to release a working Google-4-TbSync in this weekend.

Thanks,
MZ

**Comment by MSBlueVn** [comment]
Any idea when it will be available in the thunderbird add-ons store?

**Comment by zanonmark** [comment]
Released yesterday and available since today.

Thanks,
MZ
