### ISSUE TITLE
Unable to add to TBSync

### ISSUE THREAD

**Issue by jeremymeyers** [zanonmark/Google-4-TbSync#6]
Hey there-
I followed the directions (created the APIetc), and "google's people api" does show up on the "add new account" menu, but after filling in id/secret/read only it doesn't actually get added to the  accounts list and the list still says "there are no accounts defined".  It does not seem to throw an error either, as the event log is empty

**Comment by zanonmark** [comment]
Sorry it was a silly bug.
Fixed now.

Thanks,
MZ
