### ISSUE TITLE
G4TbS 0.60 works perfectly on other machines, sync stops working on one machine only?

### ISSUE THREAD

**Issue by Rotaryracer** [zanonmark/Google-4-TbSync#62]
Weird issue here, as the app works perfectly on my Windows 10 desktop and laptop and previously was working fine on my Windows 11 laptop.  Unfortunately, the latter is now no longer allowing synchronization.  I am running Thunderbird 102.15.1 with the G4TbS 0.60 add-on.  Google Cloud API seems to be fine and enabled, ID and secret key is correct and unchanged, and the exact same settings work perfectly on other machines with no sync issues.  I've tried to disable/re-enable as well as remove and re-add the Google account but keep getting the same error message.  I don't see any sync/Google login pop-ups on this machine, not even a "flash" of one that tries to open and then closes.  Any thoughts on how I managed to break this? 

Thanks in advance...

![G4TBS-1](https://github.com/zanonmark/Google-4-TbSync/assets/80466327/3d815d4b-64b5-48ca-b984-c3646caa5b96)
![G4TBS-2](https://github.com/zanonmark/Google-4-TbSync/assets/80466327/b60564c4-32ba-42ce-9db3-5dee03008860)

**Comment by Chef8** [comment]
Update. I was able to successfully fix this issue by copying my working TB profile to my non-working computer. After copying the profile, restarted TB, had to uninstall both extensions, restart TB, install both extensions. All extension settings were retained. I was able to successfully connect and sync with both of my google accounts.

If you do not having a working TB profile to copy, you may need to troubleshoot on your own. I noticed that after uninstalling the extensions and restarting TB, then reinstalling the extensions, that all data was retained. This makes me think that uninstalling TB extensions does not completely uninstall them. There may be a manual way to fully uninstall TB extensions, and this is what I would try first for anyone else having this issue. Just have your Google Client ID and Secret ready for when you install the TBSync extension.

**Comment by zanonmark** [comment]
Thanks to @Rotaryracer for reporting this issue and to @Chef8 for providing a fast workaround.

@Rotaryracer: did the suggested fix work for You too?
If so, I can't say what actually happened - maybe some updated screwed something?
If not, we can try and investigate further...

@Chef8: the data is currently saved by TbSync itself, so uninstalling and reinstalling Google-4-TbSync should actually keep your settings. Things may change in the future.

Thanks,
MZ

**Comment by Rotaryracer** [comment]
Hi all - thanks very much for the help and suggestions!  I wasn’t able to try @Chef8’s suggestion yet, but did have a few minutes to fire up the machine and try to sync one last time.

Naturally, it worked like a champ.  🤪

The Google security/authorization window loaded as expected and allowed me to authorize and grant permissions.  Previously, that was the stopping point - it would not show that pop-up window.  I don’t use this machine a lot, so maybe it got too far outside of an authentication timeframe?  In any event, it appears to be working again.  If the issue should reoccur, I’ll note it and try using @Chef8 ’s fix.

Thanks again!

**Comment by zanonmark** [comment]
@Chef8: 

> Marco, might I suggest possible adding an option in the future to reset/restore/clear TBSync data related to the Google OAuth, but preserving the Google Client ID and secret?

Nice idea.
But TbSync is going to be merged into TB itself, so the future versions of Google-4-TbSync will work on top of TB (not TbSync). I currently don't know how such internal data will be managed by TB.

I'm closing the ticket because the original issue seems solved. Feel free to reopen if it persists.

Thanks,
MZ
