### ISSUE TITLE
Login using email and password

### ISSUE THREAD

**Issue by humbertleonardo** [zanonmark/Google-4-TbSync#7]
Is there any way to log in without having to create a set of API credentials? Just using your email and password, just like TBSync, Gcontacts or CardBook?

**Comment by zanonmark** [comment]
Hi,

I'm sorry, as far as I know it can't be done with Google protocols: they require an OAuth authentication.
The same was / is for gContactSync.
(The other plugins You mentioned probably use a standard CardDAV protocol.)

Thanks,
MZ
