### ISSUE TITLE
Unable to get this to work

### ISSUE THREAD

**Issue by bkarlan** [zanonmark/Google-4-TbSync#9]
I wrote a review and you responded, thank you.  However, I cannot respond back to you that way.  I tried your updated instructions, but I fail in the 1st section.  I cannot get past location under organization.  I have no organization as you do, but then I have location request that is mandatory to answer and I cannot select anything.  So I cannot go further.

![image](https://user-images.githubusercontent.com/2250480/117182708-50617600-ad9c-11eb-879f-672e8b8b5774.png)

**Comment by zanonmark** [comment]
Hi,

actually I don't have "Organization: No organization", but "Location: No organization".
I simply don't have the "Organization" field.

Could You please tell me what's in that (Organization) combo box?

Thanks,
MZ

**Comment by zanonmark** [comment]
Hi,

can these links be helpful:
https://cloud.google.com/resource-manager/docs/creating-managing-organization
https://console.cloud.google.com/iam-admin/cloudidentity/consumer
?

You should be able to list the properties in Your Organization, and possibly the Locations.

Thanks,
MZ

**Comment by zanonmark** [comment]
Hi,

is there any news on this issue?

MZ

**Comment by zanonmark** [comment]
Closing because of many weeks without reply.

Feel free to reopen if the problem persists.

MZ
